modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "logicchips"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.logicchips]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicchips]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.logicchips]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.68,)"
ordering = "AFTER"
side = "BOTH"